### ISSUE TITLE
UPDATE: show requiered fields

### ISSUE THREAD

**Issue by gianniaubry** [aubrydario/symfony4_accounting#6]
If you add a new customer, application user would like to show all required fields that are mandatory.
Show them with a red star and a legend text at the end of the form.  (e.g Diese Felder sind erforderlich)
These fields are mandatory:
Geschlecht, Name, Vorname, Geburtstag, Strasse, Nr., PLZ, Ort, Eintritt

**Comment by aubrydario** [comment]
Fixed in 5b67143
